-- Startino Themes — Neptune ♆
-- Generated by prism. Do not edit by hand.
--
-- Returns the palette as a table, so requiring files get it explicitly rather
-- than relying on globals (each require() is its own Lua scope):
--
--   local neptune = require("shared/colors/startino-neptune")
--   col = { inactive_border = neptune.inactive_border }
--
-- Hyprland color syntax: rgba(RRGGBBAA), rgb(RRGGBB), or 0xAARRGGBB.

-- Brand pair — used for the active-window border gradient (mint → pink).
local brand_primary   = "rgba(45dfa4ff)"
local brand_secondary = "rgba(ffbfdaff)"

return {
  brand_primary   = brand_primary,
  brand_secondary = brand_secondary,
  active_border_a = brand_primary,
  active_border_b = brand_secondary,

  -- Surface palette.
  inactive_border = "rgba(4e6565ff)",
  background      = "rgba(102424ff)",
  shadow          = "rgba(091717ff)",

  -- Group/tab borders (when using grouped windows).
  group_active    = brand_primary,
  group_inactive  = "rgba(2e4343ff)",
  group_locked    = "rgba(ff8496ff)",
}
