-- Per-app opacity, disabled by default. Enable by uncommenting:
-- hl.window_rule({ match = { class = "^(firefox)$" }, opacity = "0.90 0.90" })
-- hl.window_rule({ match = { class = "^(kitty)$" },   opacity = "0.90 0.90" })
