#!/usr/bin/env bash

remove() {
	# User Configs
	rm -rf ~/.config/hypr
	rm -rf ~/.config/eww
	rm -rf ~/.config/i3
	rm -rf ~/.config/kitty
	rm -rf ~/.config/nvim
	rm -rf ~/.config/tofi
	rm -rf ~/.config/waybar

	# Fonts
	rm -rf ~/.local/share/fonts

	# Root Configs
	sudo rm -rf /root/.config/nvim
}

create() {
	# User Configs
	mkdir -p ~/.config/
	mkdir -p ~/.config/hypr

	ln -s ~/nix-config/dotfiles/hypr/users ~/.config/hypr/users
	ln -s ~/nix-config/dotfiles/hypr/hosts ~/.config/hypr/hosts
	ln -s ~/nix-config/dotfiles/hypr/shared ~/.config/hypr/shared
	./hypr.sh # source correct hypr files

	ln -s ~/nix-config/dotfiles/eww ~/.config/eww
	ln -s ~/nix-config/dotfiles/i3 ~/.config/i3
	ln -s ~/nix-config/dotfiles/kitty ~/.config/kitty
	ln -s ~/nix-config/dotfiles/nvim ~/.config/nvim
	ln -s ~/nix-config/dotfiles/tofi ~/.config/tofi
	ln -s ~/nix-config/dotfiles/waybar ~/.config/waybar

	# The Tmux Config itself is generated by nix but the plugin files need to be symlinked
	for file in ~/nix-config/dotfiles/tmux/*; do
		target_file=~/.config/tmux/$(basename "$file")
		if [ ! -e "$target_file" ]; then
			ln -s "$file" "$target_file"
		else
			echo "Skipping $file: File already exists in target directory."
		fi
	done

	# Fonts
	ln -s /run/current-system/sw/share/X11/fonts ~/.local/share/fonts

	# Root Configs
	sudo mkdir -p /root/.config/

	sudo ln -s ~/nix-config/dotfiles/nvim /root/.config/nvim
}

remove
if ! [[ $1 == 'remove' ]]; then
	create
fi
