# █▀▀ █▀▀ █▄ █ █▀▀ █▀█ ▄▀█ █  
# █▄█ ██▄ █ ▀█ ██▄ █▀▄ █▀█ █▄▄

general {
  gaps_in = 0
  gaps_out = 0
  border_size = 0
  col.active_border = $startino_active_border_a $startino_active_border_b 45deg
  col.inactive_border = $startino_inactive_border
  layout = dwindle
  # cursor_inactive_timeout = 0 
  # no_focus_fallback = false 
  # resize_on_border = false 
}
