windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$

# general {
#     allow_tearing = true
# }

#windowrulev2 = immediate, class:^(deadcells)$
