# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █ █ ██▄ █▄▄
#exec-once = eww
#exec-once = swww init

# Programs
#exec-once=[workspace 1 ]


exec-once=[workspace 7 ]
exec-once=[workspace 7 ] steam steam://rungameid/1147690


exec-once=[workspace 1 silent] spotify
exec-once=[workspace 1 silent] helvum # whatever music program here too in personal config
exec-once=[workspace 2 silent] webcord
exec-once=[workspace 3 silent] signal-desktop
exec-once=[workspace 5 silent] brave https://configure.zsa.io/my_layout/view/7q6Nx
#exec-once=[workspace 3 silent] caprine
#exec-once=[workspace 4 silent] obsidian
#exec-once=[workspace 4 silent] firefox
#exec-once=[workspace 7 ] firefox
#exec-once=[workspace 8 silent] firefox
exec-once=[workspace 9 silent] firefox
exec-once=[workspace 10 silent] kitty

