{ pkgs, config, lib, ... }:
let
  resurrectDirPath = "~/.config/tmux/resurrect";
  generatedConfigFilePath = "~/.config/tmux/tmux.conf"; # Generated by extraConfig
  tmux-nerd-font-window-name = pkgs.tmuxPlugins.mkTmuxPlugin {
    pluginName = "tmux-nerd-font-window-name.tmux";
    version = "unstable-2023-08-22";
    rtpFilePath = "tmux-nerd-font-window-name.tmux";
    src = pkgs.fetchFromGitHub {
      owner = "joshmedeski";
      repo = "tmux-nerd-font-window-name";
      rev = "c2e62d394a290a32e1394a694581791b0e344f9a";
      sha256 = "stkhp95iLNxPy74Lo2SNes5j1AA4q/rgl+eLiZS81uA=";
    };
  };
in
{
    config = {

        home.packages = with pkgs; [
            sesh
        ];

        programs.tmux = {
            enable = true;
            secureSocket = false;
            terminal = "screen-256color";
            disableConfirmationPrompt = true;
            prefix = "C-a";
            keyMode = "vi";
            baseIndex = 1;
            clock24 = true;
            sensibleOnTop = true;
            shell = "${pkgs.fish}/bin/fish";
            historyLimit = 100000;
            mouse = true;

            # Important notice about tmux plugins and the tmux.conf that generated from
            # this tmux.nix
            #
            # in general plugins may and will conflict with each other, so the order in
            # which tmux loads them matters.  This is true when editing directly tmux.conf
            # and same applies when putting them in the plugins list in NixOS.
            #
            # Specifically in my current list. The theme plugin(nord) must be included before
            # continuum and same is true for everything that might set tmux status-right
            # as the auto save command(set -g @continuum-save-interval '1')
            # gets written into status-right. So everything that sets status-right would have to be loaded
            # beforehand.
            # Furthermore the continuum plugin must be loaded after the resurrect plugin.

            plugins = with pkgs.tmuxPlugins; [
                # The theme should on the top of the list of the plugins. As it 
                # writes into the status-right which breaks the
                # `set -g @continuum-save-interval` for the continuum plugin.
                {
                    plugin = catppuccin;
                    extraConfig = ''
                        set -g @catppuccin_flavour 'mocha'
                        set -g @catppuccin_window_left_separator "█"
                        set -g @catppuccin_window_right_separator "█ "
                        set -g @catppuccin_window_middle_separator " █"
                        set -g @catppuccin_window_number_position "right"

                        set -g @catppuccin_window_default_fill "number"
                        set -g @catppuccin_window_default_text "#W"

                        set -g @catppuccin_window_current_fill "number"
                        set -g @catppuccin_window_current_text "#W"

                        set -g @catppuccin_status_modules "application session user host battery date_time"
                        set -g @catppuccin_status_left_separator  ""
                        set -g @catppuccin_status_right_separator ""
                        set -g @catppuccin_status_right_separator_inverse "no"
                        set -g @catppuccin_status_fill "icon"
                        #set -g @catppuccin_status_connect_separator "no"

                        set -g @catppuccin_directory_text "#{pane_current_path}"
                    '';
                }

                {
                    plugin = better-mouse-mode;
                }

                # Required for catppuccin battery indicator
                {
                    plugin = battery;
                }
                {
                    plugin = resurrect;
                    extraConfig = ''

                    # I have tested this strategy to work with neovim but it is not enough to have
                    # Session.vim at the root of the path from which the plugin is going to do the restore
                    # it is important that for neovim to be saved to be restored from the path where Session.vim
                    # exist for this flow to kick in. Which means that even if tmux-resurrect saved the path with
                    # Session.vim in it but vim was not open at the time of the save of the sessions then when
                    # tmux-resurrect restore the window with the path with Session.vim nothing will happen.

                    # Furthermore I currently using vim-startify which among other things is able to restore
                    # from Session.vim if neovim is opened from the path where Session.vim exist. So in a
                    # sense I don't really need tmux resurrect to restore the session as this already
                    # taken care of and this functionality becomes redundant. But as I am not sure if I keep
                    # using vim-startify or its auto restore feature and it do not conflict in any way that
                    # I know of with set -g @resurrect-strategy-* I decided to keep it enabled for the time being.
                    set -g @resurrect-strategy-nvim 'session'
                    set -g @resurrect-strategy-vim 'session'

                    set -g @resurrect-capture-pane-contents 'on'

                    # This three lines are specific to NixOS and they are intended
                    # to edit the tmux_resurrect_* files that are created when tmux
                    # session is saved using the tmux-resurrect plugin. Without going
                    # into too much details the strings that are saved for some applications
                    # such as nvim, vim, man... when using NixOS, appimage, asdf-vm into the
                    # tmux_resurrect_* files can't be parsed and restored. This addition
                    # makes sure to fix the tmux_resurrect_* files so they can be parsed by
                    # the tmux-resurrect plugin and successfully restored.
                    set -g @resurrect-dir ${resurrectDirPath}
                    set -g @resurrect-hook-post-save-all 'target=$(readlink -f ${resurrectDirPath}/last); sed "s| --cmd .*-vim-pack-dir||g; s|/etc/profiles/per-user/$USER/bin/||g" $target | sponge $target'
                    '';
                }

                # The copy buffer for tmux is separate from the system one, in the past in
                # order to sync the two there was a need to install tmux-yank but it looks like
                # Tmux now sends the OSC52 escape code that tells the terminal(one that support this)
                # to not display the following characters, but to copy them into the clipboard
                # instead.
                #
                # The reason that this plugin is still included because it provides a quick way to copy what
                # what is on the command line and once in copy mode to copy the PWD. I might just replace the
                # plugin with keybindings(based on send-keys).
                {
                    plugin = yank;
                }
                # For some reason this plugin by default only copy into the Tmux copy buffer
                # and so I had to explicitly state the command to make it copy into the system
                # clipboard as swell.
                {
                    plugin = tmux-thumbs;
                    extraConfig = ''
                    set -g @thumbs-command 'tmux set-buffer -- {} && tmux display-message "Copied {}" && printf %s {} | xclip -i -selection clipboard'
                    set -g @thumbs-key C-y
                    '';
                }
                {
                    plugin = extrakto;
                    extraConfig = ''
                        set -g @extrakto_key M-y
                        set -g @extrakto_split_direction v
                    '';
                }
                # a few words about @continuum-boot and @continuum-systemd-start-cmd that
                # are not used as part of the extraConfig for the continuum plugin.
                #
                # @continuum-boot - when set will generate a user level systemd unit file
                # which it will save to ${HOME}/.config/systemd/user/tmux.service and enable
                # it.
                #
                # @continuum-systemd-start-cmd - The command used to start the tmux server
                # is determined via this configuration, and this command is set in the
                # context of the systemd unit file that is generated by setting @continuum-boot
                # when this option is not set the default will be "tmux new-session -d"
                # This setting provides a more fine grain option over the creation of the
                # systemd unit.
                #
                # Having said all that, it is important to understand that systemd units
                # are defined as .nix settings and then created when NixOS is built and
                # nothing is generated "willy-nilly" by applications.
                # So this aspect of the plugin is already taken care of by me in a separate
                # systemd unit that is responsible to start tmux when system starts.
                #
                # set -g @continuum-save-interval is written into the status-right which
                # means that any other plugin that writes into status-right needs to be
                # loaded first or the autosave functionality will not work.
                #
                # More then that it looks like the autosave feature(set -g @continuum-save-interval)
                # only works if you are attached to tmux, for some reason it does not work
                # in detached mode. Maybe if no one is attached then there is nothing
                # changing and so nothing to save.
                #
                # If autosave option interval is not set there is a default of 15 minutes
                # and it worked for me when tested.
                {
                plugin = continuum;
                    extraConfig = ''
                        set -g @continuum-restore 'on'
                        set -g @continuum-save-interval '10'
                    '';
                }
                {
                    plugin = tmux-nerd-font-window-name;
                    extraConfig = ''
                        set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
                    '';
                }
            ];
            extraConfig = ''
                # This command is executed to address an edge case where after a fresh install of the OS no resurrect
                # directory exist which means that the continuum plugin will not work. And so without user
                # manually saving the first session(prfix + Ctrl+s) no resurrect-continuum will occur.
                #
                # And in case user does not remember to save his work for the first time and tmux daemon gets
                # restarted next time user will try to attach, there will be no state to attach to and user will
                # be scratching his head as to why.
                #
                # Saving right after fresh install on first boot of the tmux daemon with no sessions will create an
                # empty "last" session file which might cause all kind of issues if tmux gets restarted before
                # the user had the chance to work in it and let continuum plugin to take over and create
                # at least one valid "snapshot" from which tmux will be able to resurrect. This is why an initial
                # session named init-resurrect is created for resurrect plugin to create a valid "last" file for
                # continuum plugin to work off of.
                run-shell "if [ ! -d ${resurrectDirPath} ]; then tmux new-session -d -s init-resurrect; ${pkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/scripts/save.sh; fi"

                set -ag terminal-overrides ",xterm-256color:RGB"

                # sets the length of session name
                set -g status-left-length 30

                # don't detach from tmux once last window of session is closed and instead
                # attach to another existing session if one exist.
                set-option -g detach-on-destroy off

                # Ensure window index numbers get reordered on delete
                set-option -g renumber-windows on

                # Quicker escape in neovim
                set -sg escape-time 0
                set-option -g set-titles on
                set-option -g set-titles-string "#S / #W"

                # Change splits to match nvim and easier to remember
                # Open new split at cwd of current split
                unbind %
                unbind '"'
                bind | split-window -h -c "#{pane_current_path}"
                bind - split-window -v -c "#{pane_current_path}"

                # Use vim keybindings in copy mode
                set-window-option -g mode-keys vi

                # vim idiomatic selection and yanking
                # ==================================
                # This section is done in addition to the yanking plugins I already installed
                # as those plugins are "one shot yank" intended to achieve something
                # very specific while the following keybindings are intended to select and yank
                # text the same way you will do in vim.
                #
                # Comparing to vim, tmux starts in INSERT mode and by executing prefix+[
                # tmux goes into NORMAL mode and the following keybindings mimic
                # selecting text in vim NORMAL mode.

                # Go into selection and once done press Enter or y to yank
                # -----------------
                # Go into selection mode(vim VISUAL mode)
                # to yank selected.
                bind-key -T copy-mode-vi v send-keys -X begin-selection
                #
                # Go into selection mode of line(vim VISUAL LINE mode)
                bind-key -T copy-mode-vi V send-keys -X select-line
                #
                # Go into rectangle selection mode(vim VISUAL BLOCK mode)
                bind-key -T copy-mode-vi C-v run-shell 'tmux send-keys -X rectangle-toggle; tmux send-keys -X begin-selection'

                # Yanking
                # -------
                # This is the action that tapping the Enter key will do by default for tmux
                # The only reason this is here is because this is how yanking is done
                # vim.
                # I created costume keybinding that removes \n when coping a line.
                # not sure if it might break some flow and it requires perl and xclip.
                # so I left the version that adds \n and has no dependencies in comment.
                #bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
                bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "perl -pe 'chomp if eof' | tmux load-buffer - ; tmux save-buffer - | xclip -i -selection clipboard"
                # ==================================

                # Escape turns on copy mode
                bind Escape copy-mode

                # Easier reload of config
                bind r source-file ~/.config/tmux/tmux.conf

                set-option -g status-position top

                # make Prefix p paste the buffer.
                unbind p
                bind p paste-buffer

                set -g allow-passthrough on
                set -ga update-environment TERM
                set -ga update-environment TERM_PROGRAM

                bind-key -T copy-mode-vi M-h resize-pane -L 1
                bind-key -T copy-mode-vi M-j resize-pane -D 1
                bind-key -T copy-mode-vi M-k resize-pane -U 1
                bind-key -T copy-mode-vi M-l resize-pane -R 1

                # Bind Keys
                bind-key -T prefix C-g split-window \
                    "$SHELL --login -i -c 'navi --print | head -c -1 | tmux load-buffer -b tmp - ; tmux paste-buffer -p -t {last} -b tmp -d'"
                bind-key -T prefix C-l switch -t notes
                bind-key -T prefix C-d switch -t dotfiles
                bind-key e send-keys "tmux capture-pane -p -S - | nvim -c 'set buftype=nofile' +" Enter

                # evaluate/reload config
                bind-key e source-file ${generatedConfigFilePath} \; display-message "${generatedConfigFilePath} evaluated."
            '';
        };
    };
}
