source = ~/.config/hypr/shared/colors/startino-neptune.conf
source = ~/.config/hypr/shared/themes/default/**.conf
source = ~/.config/hypr/shared/workflow/default/**.conf
source = ~/.config/hypr/shared/workflow/default/binds/dvp.conf
source = ~/.config/hypr/shared/utility/**.conf
source = ~/.config/hypr/users/eksno/default/**.conf

bind = CTRL ALT, r, exec, phonetic --trigger r
bind = CTRL ALT, c, exec, phonetic --trigger c
bind = CTRL ALT, g, exec, phonetic --trigger g
