# Programs
exec-once=[workspace 9] kitty

# exec-once=[workspace 1 silent] helvum
# exec-once=[workspace 1 silent] easyeffects
# exec-once=[workspace 2 silent] discord
# exec-once=[workspace 3 silent] firefox
# exec-once=[workspace 12 silent] firefox chat.openai.com
# exec-once=[workspace 11 silent] firefox mail.proton.me
# exec-once=[workspace 8 silent] firefox localhost:5173
# exec-once=[workspace 15 silent] firefox app.plane.so/futino
