input {
  kb_layout = us,no
  kb_variant = dvp,
  kb_model =
  kb_options = grp:win_space_toggle
  kb_rules =

  follow_mouse = 1

  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  # accel_profile = flat # gtfo mouse acceleration
  accel_profile = adaptive # okay fiiiine it's better here

  touchpad {
    natural_scroll = yes
  }
}
