decoration {
  # █▀█ █▀█ █ █ █▄ █ █▀▄   █▀▀ █▀█ █▀█ █▄ █ █▀▀ █▀█
  # █▀▄ █▄█ █▄█ █ ▀█ █▄▀   █▄▄ █▄█ █▀▄ █ ▀█ ██▄ █▀▄
  rounding = 0
  # multisample_edges = true

  # █▀█ █▀█ ▄▀█ █▀▀ █ ▀█▀ █▄█
  # █▄█ █▀▀ █▀█ █▄▄ █  █   █ 
  active_opacity = 1.0
  inactive_opacity = 1.0

  # █▄▄ █   █ █ █▀█
  # █▄█ █▄▄ █▄█ █▀▄
  blur {
    enabled = true
    size = 6
    passes = 3
    new_optimizations = true
    xray = true
    ignore_opacity = true
  }

  # █▀ █ █ ▄▀█ █▀▄ █▀█ █ █ █
  # ▄█ █▀█ █▀█ █▄▀ █▄█ ▀▄▀▄▀
  #blurls = gtk-layer-shell
  blurls = waybar
  blurls = lockscreen
}
