# Zen workspace restore
exec-once = ~/.config/hypr/shared/scripts/zen-workspace-restore.sh
exec-once = ~/.config/hypr/shared/scripts/zen-workspace-save.sh

# Programs
exec-once=[workspace 9] kitty
exec-once = zen-beta
exec-once = discord
exec-once = [workspace 16 silent] protonvpn-app

# Window rules
windowrule = match:class discord, workspace 2 silent
