# Programs
exec-once=[workspace 9] kitty
exec-once = discord
exec-once = [workspace 16 silent] protonvpn-app
exec-once = bash -c 'sleep 3 && hyprctl dispatch exec "[workspace 16 silent] bitwarden"'

# Window rules
windowrule = match:class discord, workspace 2 silent
