# System
exec-once=waybar

# Toggle waybar
bind = $mainMod, b, exec, pkill -SIGUSR1 waybar || waybar &

# Startup apps
exec-once=[workspace 4] kitty
exec-once=[workspace 5 silent] google-chrome-stable
exec-once=[workspace 3 silent] discord
