# System
exec-once=waybar

# Toggle waybar
bind = $mainMod, b, exec, pkill -SIGUSR1 waybar || waybar &

# Brightness (min 5%)
bind = , XF86MonBrightnessDown, exec, brightnessctl -n 5% set 5%-
bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+

# Startup apps
exec-once=[workspace 4] kitty
exec-once=[workspace 5 silent] google-chrome-stable
exec-once=[workspace 3 silent] discord
