# Programs
exec-once=[workspace 1 silent] helvum
exec-once=[workspace 1 silent] easyeffects
exec-once=[workspace 7] kitty
exec-once=[workspace 2 silent] firefox -new-tab -url supabase.com/dashboard/projects
exec-once=[workspace 3 silent] firefox -new-tab -url discord.com/app 
exec-once=[workspace 5 silent] firefox -new-tab -url chat.openai.com -new-tab -url platform.openai.com/usage
exec-once=[workspace 8 silent] firefox -new-tab -url localhost:5173 -new-tab -url 127.0.0.1:8000
exec-once=[workspace 9 silent] firefox -new-tab -url app.clockify.me/tracker
exec-once=[workspace 11 silent] firefox -new-tab -url mail.proton.me
exec-once=[workspace 12 silent] spotify
exec-once=[workspace 14 silent] firefox -new-tab -url app.plane.so/futino
