# Programs
exec-once=[workspace 1 silent] helvum
exec-once=[workspace 1 silent] easyeffects
exec-once=[workspace 2 silent] firefox supabase.com/dashboard/projects
exec-once=[workspace 3 silent] discord
exec-once=[workspace 4 silent] firefox
exec-once=[workspace 5 silent] firefox chat.openai.com
exec-once=[workspace 11 silent] firefox mail.proton.me
exec-once=[workspace 12 silent] spotify
exec-once=[workspace 6 silent] code ~/vcs/futino/aitino
exec-once=[workspace 15 silent] code ~/vcs/futino/futino
exec-once=[workspace 7] kitty
exec-once=[workspace 8 silent] firefox localhost:5173
exec-once=[workspace 14 silent] firefox app.plane.so/futino
