# Programs
exec-once=[workspace 1 silent] helvum
exec-once=[workspace 1 silent] easyeffects
exec-once=[workspace 7] kitty
exec-once=[workspace 2 silent] firefox --new-window supabase.com/dashboard/projects
exec-once=[workspace 3 silent] firefox --new-window  discord.com/app 
exec-once=[workspace 5 silent] firefox --new-window -url chat.openai.com -url platform.openai.com/usage
exec-once=[workspace 8 silent] firefox --new-window -url localhost:5173 -url 127.0.0.1:8000
exec-once=[workspace 9 silent] firefox --new-window app.clockify.me/tracker
exec-once=[workspace 11 silent] firefox --new-window -url mail.proton.me -url calendar.proton.me
exec-once=[workspace 12 silent] spotify
exec-once=[workspace 13 silent] firefox --new-window app.gather.town
exec-once=[workspace 14 silent] firefox --new-window app.plane.so/futino
