source = ~/.config/hypr/users/teto/themes/**.conf
source = ~/.config/hypr/users/teto/workflow/**.conf
source = ~/.config/hypr/shared/workflow/default/binds/voyager2H.conf
source = ~/.config/hypr/users/teto/utility/**.conf

# startup
#source = ~/.config/hypr/users/teto/utility/startup.conf



# personal
#source = ~/.config/hypr/users/teto/monitor.conf
#source = ~/.config/hypr/users/lucy/startup.conf
# source = ~/.config/hypr/users/lucy/lucyalpha.conf
# source = ~/.config/hypr/users/lucy/pics.conf
