general {
    layout = master
}

master {
    allow_small_split = false
    special_scale_factor = 1
    mfact = 0.55
    new_is_master = false
    new_on_top = false
    no_gaps_when_only = 0
    orientation = top
    inherit_fullscreen = true
    always_center_master = false
    smart_resizing = true
    drop_at_cursor = false
}





#master {
#    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
#    new_is_master = true
#}
