# System
exec-once=waybar

# Toggle waybar
bind = $mainMod, b, exec, pkill -SIGUSR1 waybar || waybar &

# Brightness (min 5%)
bind = , XF86MonBrightnessDown, exec, bash -c 'MIN=$(( $(brightnessctl max) / 20 )); brightnessctl set 5%-; [ $(brightnessctl get) -lt $MIN ] && brightnessctl set $MIN'
bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+

# Toucan keyboard cheatsheet (persistent overlay)
exec-once = eww open keyboard-cheatsheet
bind = $mainMod CTRL, k, exec, eww open --toggle keyboard-cheatsheet

# Startup apps
exec-once=[workspace 4] kitty
exec-once=[workspace 5 silent] google-chrome-stable
exec-once=[workspace 3 silent] discord
